### ISSUE TITLE
KeyError: 'text_lower' when running step3 in python3?

### ISSUE THREAD

**Issue by brianwu02** [PhantomInsights/subreddit-analyzer#4]
I haven't made any modifications other than moving stopwords from assets to scripts (some issue with file permissions when i don't)

I see this error when running step3:

```
➜  scripts git:(master) ✗ python3 step3.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'text_lower'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "step3.py", line 589, in <module>
    generate_most_common_entities_word_cloud(comments_df)
  File "step3.py", line 541, in generate_most_common_entities_word_cloud
    df = df[~df["text_lower"].isin(stopwords)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'text_lower'
```

the main func looks like:
```
if __name__ == "__main__":

    submissions_df = pd.read_csv("mexico-submissions.csv",
                           parse_dates=["datetime"], index_col=0)

    comments_df = pd.read_csv("mexico-comments.csv",
                              parse_dates=["datetime"], index_col=0)

    tokens_df = pd.read_csv("tokens.csv")
    entities_df = pd.read_csv("entities.csv")
    generate_most_common_entities_word_cloud(comments_df)
```

**Comment by agentphantom** [comment]
you almost got it right, just change the dataframe in the function, it is the entities one instead of the comments one.
