### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by Lyfhael** [PhantomInsights/subreddit-analyzer#6]
Hi @agentphantom  ,

This is me again, sorry. I have another issue with the script.
I'm trying to download the submissions from r/goodanimemes from the last 2 weeks.

But after some time I get this error message : 
`Traceback (most recent call last):
  File "subreddit_submissions_alt.py", line 115, in <module>
    init()
  File "subreddit_submissions_alt.py", line 40, in init
    download_submissions(subreddit=subreddit)
  File "subreddit_submissions_alt.py", line 110, in download_submissions
    download_submissions(subreddit, latest_timestamp)
  File "subreddit_submissions_alt.py", line 110, in download_submissions
    download_submissions(subreddit, latest_timestamp)
  File "subreddit_submissions_alt.py", line 110, in download_submissions
    download_submissions(subreddit, latest_timestamp)
  [Previous line repeated 80 more times]
  File "subreddit_submissions_alt.py", line 72, in download_submissions
    json_data = response.json()
  File "C:\Python38\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

So I tried to launch the script again and I get the same error message but this line `  [Previous line repeated 80 more times] ` changed to `[Previous line repeated 24 more times]` (it's a random number everytime).

_I'm no JS programmer but my wild guess is that at some point, response.json() does not receive the right parameters, program does not know how to handle it and it causes it to stop._

Do you have any fix for this ?
Thank you !

**Comment by agentphantom** [comment]
Hi,

I also get this error sometimes, my theory is that is an issue with the API. What I do is to add more delay to the sleeps, around 1.5 - 2.0 seconds.

As a side note, this was run for one year of data in a medium sized subreddit without issues. But a few months ago since they changed the rate limits of the API it started to fail more often.

**Comment by Lyfhael** [comment]
> Hi,
> 
> I also get this error sometimes, my theory is that is an issue with the API. What I do is to add more delay to the sleeps, around 1.5 - 2.0 seconds.

Yeah that must be it, and I must be somewhat very rate limited.
My last tries in order : 
- Managed to download 27 * 100 submissions.
- Managed to download 10 * 100 submissions.
- Managed to download 5 * 100 submissions.
- Managed to download 1 * 100 submissions.

And finally last try I couldn't even download the last 100.
Imma wait a bit and try to change the delay as you suggested

**Comment by Lyfhael** [comment]
UPDATE:
I noticed response code when it works is 200, and when it doesn't work it's 525, 522 and another 5xx something I don't remember.
I made a little fix so it retries the request instead of crashing and not saving the already fetched submissions. Tell me if you see anything wrong in it(it doesn't crash anymore but I'm concerned about the L_TIMESTAMP) : 

I added `L_TIMESTAMP = 0` as a global variable.
In **def download_submissions(subreddit, latest_timestamp=None):** I added `global L_TIMESTAMP`
In **with requests.get(base_url, params=params, headers=HEADERS, ) as response:** I added : 
print(response.status_code);
if response.status_code != 200:
print("ERROR - Retrying. . .")
time.sleep(1.5)
download_submissions(subreddit, L_TIMESTAMP)
return

And modified this
else:
    **L_TIMESTAMP = latest_timestamp**
        time.sleep(2.1)
        download_submissions(subreddit, latest_timestamp)

Here is how it looks when an error occurs in console : https://i.imgur.com/XohU6nL.png

EDIT: Ok I forgot to add a **return** when the response code is != 200 or at the end of the recursive it'll still try to process those broken requests...

**Comment by agentphantom** [comment]
That's a really nice fix. It should work since L_TIMESTAMP will always be the latest successful timestamp.

5xx errors are in the range of server errors.

**Comment by Lyfhael** [comment]
> That's a really nice fix. It should work since L_TIMESTAMP will always be the latest successful timestamp.
> 
> 5xx errors are in the range of server errors.

<3

I got one last issue then everything will be working perfectly.
Those two functions `generate_most_common_entities_word_cloud(df)` and `generate_most_common_words_word_cloud(df)` make step3.py crash.(All others plot_* functions work) Someone else had this issue ( https://github.com/PhantomInsights/subreddit-analyzer/issues/4 ), you responded to it but I don't understand what I need to modify.

Here is the main function : 
```
if __name__ == "__main__":

    df = pd.read_csv("goodanimemes-submissions.csv",
                           parse_dates=["datetime"], index_col=0)

    df2 = pd.read_csv("goodanimemes-comments.csv",
                              parse_dates=["datetime"], index_col=0)

    tokens_df = pd.read_csv("tokens.csv")
    entities_df = pd.read_csv("entities.csv")
    #generate_most_common_entities_word_cloud(df)
    generate_most_common_words_word_cloud(df)
    #plot_comments_by_user(df)
    #plot_submissions_by_user(df)
    #plot_yearly_submissions_and_comments(df, df2)
    #plot_submissions_and_comments_by_hour(df, df2)
   # plot_submissions_and_comments_by_weekday(df, df2)
```

For the first function the traceback is : 
```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2889, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 97, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'text_lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\hteis\Desktop\subreddit-analyzer-master\scripts\step3.py", line 586, in <module>
    generate_most_common_entities_word_cloud(df)
  File "C:\Users\hteis\Desktop\subreddit-analyzer-master\scripts\step3.py", line 538, in generate_most_common_entities_word_cloud
    df = df[~df["text_lower"].isin(stopwords)]
  File "C:\Python38\lib\site-packages\pandas\core\frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: 'text_lower'
```

For the second function the traceback is : 
```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2889, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 97, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'lemma_lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hteis\Desktop\subreddit-analyzer-master\scripts\step3.py", line 587, in <module>
    generate_most_common_words_word_cloud(df)
  File "C:\Users\hteis\Desktop\subreddit-analyzer-master\scripts\step3.py", line 482, in generate_most_common_words_word_cloud
    df = df[~df["lemma_lower"].isin(stopwords)]
  File "C:\Python38\lib\site-packages\pandas\core\frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: 'lemma_lower'
```

**Comment by agentphantom** [comment]
For the first function you need to pass the tokens_df as a parameter abd for the second one you need to pass the entities_df.

You can see at the bottom of the script that we create 4 DataFrames, the two at the bottom have keys that the 2 first don't and those are the ones required by the functions that crash.

**Comment by Lyfhael** [comment]
> For the first function you need to pass the tokens_df as a parameter abd for the second one you need to pass the entities_df.
> 
> You can see at the bottom of the script that we create 4 DataFrames, the two at the bottom have keys that the 2 first don't and those are the ones required by the functions that crash.

So I called it like this `generate_most_common_entities_word_cloud(tokens_df)` (as I understand I needed to replace df by tokens_df) but I have this error : 
```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2889, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 97, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hteis\Desktop\subreddit-analyzer-master\scripts\step3.py", line 592, in <module>
    generate_most_common_entities_word_cloud(tokens_df)
  File "C:\Users\hteis\Desktop\subreddit-analyzer-master\scripts\step3.py", line 543, in generate_most_common_entities_word_cloud
    (df["label"].isin(["LOC", "ORG", "PER"])) &
  File "C:\Python38\lib\site-packages\pandas\core\frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: 'label'
```
As it's not very clear to me I tried to call all the plot_* functions first then the `generate_most_common_entities_word_cloud(tokens_df)` but still no.

I also tried to call `generate_most_common_words_word_cloud(entities_df)` (added entities_df as parameter) but I still have the `KeyError: 'lemma_lower'`

**Comment by agentphantom** [comment]
I think you switched the DataFrames. It must be as follows:

```
generate_most_common_words_word_cloud(tokens_df)
generate_most_common_entities_word_cloud(entities_df)
```

**Comment by Lyfhael** [comment]
> I think you switched the DataFrames. It must be as follows:
> 
> ```
> generate_most_common_words_word_cloud(tokens_df)
> generate_most_common_entities_word_cloud(entities_df)
> ```

... I just needed to read the entities.csv and tokens.csv and I would have realized it, my bad.
So it created a different error this time. It's trying to open a file but it doesn't find it ? I'm not sure what file could correspond
```
Traceback (most recent call last):
  File "C:\Users\hteis\Desktop\subreddit-analyzer-master\scripts\step3.py", line 593, in <module>
    generate_most_common_entities_word_cloud(entities_df)
  File "C:\Users\hteis\Desktop\subreddit-analyzer-master\scripts\step3.py", line 572, in generate_most_common_entities_word_cloud
    wc.generate(" ".join(entities_list))
  File "C:\Python38\lib\site-packages\wordcloud\wordcloud.py", line 631, in generate
    return self.generate_from_text(text)
  File "C:\Python38\lib\site-packages\wordcloud\wordcloud.py", line 613, in generate_from_text
    self.generate_from_frequencies(words)
  File "C:\Python38\lib\site-packages\wordcloud\wordcloud.py", line 446, in generate_from_frequencies
    self.generate_from_frequencies(dict(frequencies[:2]),
  File "C:\Python38\lib\site-packages\wordcloud\wordcloud.py", line 496, in generate_from_frequencies
    font = ImageFont.truetype(self.font_path, font_size)
  File "C:\Python38\lib\site-packages\PIL\ImageFont.py", line 655, in truetype
    return freetype(font)
  File "C:\Python38\lib\site-packages\PIL\ImageFont.py", line 652, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Python38\lib\site-packages\PIL\ImageFont.py", line 193, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by agentphantom** [comment]
The clouds can use any custom font but I didn't include it in the repo as I don't have the license. You have 2 opions:

1. Provide any font and rename it to 'sofiapro-light.otf' and put it in the assets folder.
2. Remove the parameter 'font_path' from both functions.

**Comment by Lyfhael** [comment]
> The clouds can use any custom font but I didn't include it in the repo as I don't have the license. You have 2 opions:
> 
> 1. Provide any font and rename it to 'sofiapro-light.otf' and put it in the assets folder.
> 2. Remove the parameter 'font_path' from both functions.

It works !!! Yes :D 
Also, I noticed generate_most_common_entities_word_cloud does not remove lines containing links so the datagram is filled with "https" "reddit" "jpg" etc.
I found we can remove those text with : `df = df[~df["text"].str.contains('http')]` in case you're interested :)

Thank you for your patience and help <3 I wish you a good day !
